export const GAME_CONFIG_VALUES = Object.freeze({
  lobbyCountdownSeconds: 7,
  matchDurationSeconds: 90,
  finalResultsSeconds: 30,
  maxPlayers: 10,
  freezeSeconds: 15,
  playerMaxHealth: 100,
  playerSpeed: 96,
  playerRadius: 11,
  hamHealAmount: 25,
  slayScore: 200,
  deathScore: -150,
  chestScore: 50,
  hamSpawnMinSeconds: 15,
  hamSpawnMaxSeconds: 60,
  maxActiveHams: 2,
  chestSpawnMinSeconds: 15,
  chestSpawnMaxSeconds: 60,
  maxActiveChests: 2,
  chestMinHits: 3,
  chestMaxHits: 5,
  attackDamage: 25,
  attackCooldownMs: 580,
  attackActiveMs: 150,
  maxInputMessagesPerSecond: 45,
  attackRange: 32,
  attackWidth: 28,
  knockbackDistance: 26,
  arenaWidth: 720,
  arenaHeight: 660,
  leaderboardWidth: 220,
  playfieldMinX: 46,
  playfieldMaxX: 674,
  playfieldMinY: 126,
  playfieldMaxY: 486,
});

export function buildGameConfig() {
  return GAME_CONFIG_VALUES;
}

export const CHARACTER_IDS = Object.freeze([
  "alchemist",
  "archer",
  "cleric",
  "druid",
  "dwarf",
  "healer",
  "hunter",
  "monk",
  "necromancer",
  "paladin",
  "ranger",
  "rogue",
  "scribe",
  "tavern-keeper",
  "warrior",
  "wizard",
]);
